pipeline {
    agent { label 'first-agents' }

    triggers {
        githubPush()
    }

    environment {
        SPRING_DATASOURCE_URL = credentials("SPRING_DATASOURCE_URL")
        SPRING_DATASOURCE_USERNAME = credentials("SPRING_DATASOURCE_USERNAME")
        SPRING_DATASOURCE_PASSWORD = credentials('SPRING_DATASOURCE_PASSWORD')

        IMAGE_NAME = "backend_manga2you"
        DOCKER_HUB_USERNAME = "saberbenhamda0"
        DOCKERHUB_TOKEN = credentials("DOCKERHUB_TOKEN")

        SNYK_TOKEN = credentials("synk_token")
        KUBECONFIG = credentials('kube-config-for-staging')
        GITHUB_TOKEN = credentials("GITHUB_TOKEN")

        ARGOCD_USERNAME = credentials("ARGOCD_USERNAME")
        ARGOCD_PASSWORD = credentials("ARGOCD_PASSWORD")
    }

    stages {

        stage('Checkout') {
            steps {
                sshagent(['PRIVATE_SSH_KEY_FOR_THE_REPO']) {
                    sh 'mkdir -p ~/.ssh'
                    sh 'ssh-keyscan github.com >> ~/.ssh/known_hosts'
                    sh 'git clone git@github.com:saberBenhamda0/backend_manga2you.git'
                }
            }
        }
        
        

        stage('Build and Run Unit Tests') {
            steps {
                sh '''
                    cd backend_manga2you
                    mvn clean install
                '''
            }

            post {
                failure {
                    slackSend(
                        channel: '#all-manga2you',
                        message: " unit test FAILED for ${env.JOB_NAME} #${env.BUILD_NUMBER}"
                    )
                }
            }
        }

        stage('OCA Scan') {
            steps {
                sh '''
                    cd backend_manga2you
                    trivy fs --severity HIGH,CRITICAL --format json --exit-code 0 .
                '''
            }

            post {
                failure {
                    slackSend(
                        channel: '#all-manga2you',
                        message: "❌ Trivy scan FAILED for ${env.JOB_NAME} #${env.BUILD_NUMBER}"
                    )
                }
            }
        }

        stage("SAST Scans") {
            steps {
                sh '''
                    cd backend_manga2you
                    snyk auth ${SNYK_TOKEN}
                    snyk code test --severity-threshold=high || true
                '''
            }

            post {
                failure {
                    slackSend(
                        channel: '#all-manga2you',
                        message: "SAST Scans Failed for ${env.JOB_NAME} ${env.BUILD_NUMBER}"
                    )
                }
            }
        }


        stage('Building The Image') {
            steps {
                sh '''
                    cd backend_manga2you
                    docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} .
                '''
            }
        }

        stage('Pushing To Docker Hub') {
            steps {
                sh '''
                    echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

                    docker tag ${IMAGE_NAME}:${BUILD_NUMBER} ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${BUILD_NUMBER}
                    docker push ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${BUILD_NUMBER}
                '''
            }
        }


        stage('Get Current Image Tag') {
            steps {
                script {
                    def currentTag = sh(
                        script: """
                            git clone https://github.com/saberBenhamda0/monolithic-devops-project.git
                            awk -F: '/image: saberbenhamda0\\/backend_manga2you/ {print \$NF}' \
                            monolithic-devops-project/infrastructure/overlays/dev/deployment.yaml
                        """,
                        returnStdout: true
                    ).trim()

                    echo "Current tag is: ${currentTag}"

                    env.CURRENT_TAG = currentTag
                }
            }
        }

        stage("promote the new docker container to both dev and staging env") {
            steps {
                sh """
                    sed -i 's#\\(image: saberbenhamda0/backend_manga2you:\\).*#\\1${env.BUILD_NUMBER}#' monolithic-devops-project/infrastructure/overlays/dev/deployment.yaml
                    sed -i 's#\\(image: saberbenhamda0/backend_manga2you:\\).*#\\1${env.BUILD_NUMBER}#' monolithic-devops-project/infrastructure/overlays/staging/deployment.yaml
                """
            }
        }

        stage('Deploy to the Cluster') {
            steps {
                sshagent(['PRIVATE_SSH_KEY_FOR_THE_REPO']) {
                    sh '''
                    cd monolithic-devops-project
                    
                    # Configure Git locally
                    git config --global user.email "saberbenhamda0@gmail.com"
                    git config --global user.name "136007584"
                    git config --global url.https://"${GITHUB_TOKEN}"@github.com/.insteadOf https://github.com/

                    git add infrastructure/overlays/dev/deployment.yaml
                    git add infrastructure/overlays/staging/deployment.yaml

                    git commit -m "Update backend image to ${BUILD_NUMBER}"
                    git push -u origin main
                    '''
                }
            }
        }

        stage("waiting for argocd to sync"){
            steps {
                sh '''
                argocd login host.docker.internal:8100 --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
                argocd app sync staging-backend-manga2you
                argocd app wait staging-backend-manga2you --sync --health --timeout 300
                '''
            }
        }

       
        stage("running k6s test on the staging env") {
            steps {
                sh """
                    kubectl delete job staging-k6-load-test-v1 -n staging --ignore-not-found
                    argocd app wait staging-backend-manga2you --sync --health --timeout 300
                """
            }

        post {
            failure {
                sh """
                    cd monolithic-devops-project
                    git revert --no-edit HEAD
                    git push origin main
                """

                sh """
                argocd app sync staging-backend-manga2you
                argocd app wait staging-backend-manga2you --sync --health --timeout 300
                """
            }
        }
        }
    }

    post {
        success {
            slackSend(
                channel: '#all-manga2you',
                message: "pipeline success FAILED for ${env.JOB_NAME} #${env.BUILD_NUMBER}"
            )
        }

        failure {
            slackSend(
                channel: '#all-manga2you',
                message: " pipeline failed for ${env.JOB_NAME} #${env.BUILD_NUMBER}"
            )
        }
    }
}