pipeline {
    agent { label 'first-agents' }
    
    triggers {
        githubPush()
    }
    
    environment {
        SPRING_DATASOURCE_URL = credentials("SPRING_DATASOURCE_URL")
        SPRING_DATASOURCE_USERNAME = credentials("SPRING_DATASOURCE_USERNAME")
        SPRING_DATASOURCE_PASSWORD = credentials('SPRING_DATASOURCE_PASSWORD') // stored as secret in Jenkins
        
        IMAGE_NAME = "backend_manga2you"
        DOCKER_HUB_USERNAME = "saberbenhamda0"
        DOCKERHUB_TOKEN = credentials("DOCKERHUB_TOKEN")
        
        SNYK_TOKEN = credentials("synk_token")
        
        GITHUB_TOKEN = credentials("GITHUB_TOKEN")

    }

    stages {

        stage('Checkout') {
            steps {
                sshagent(['PRIVATE_SSH_KEY_FOR_THE_REPO']) {
                    sh 'mkdir -p ~/.ssh'
                    sh 'ssh-keyscan github.com >> ~/.ssh/known_hosts'
                    sh 'git clone git@github.com:saberBenhamda0/backend_manga2you.git'
                }
            }
        }



            stage('Build and Run Unit Tests') {
            steps {
                sh '''
                    cd backend_manga2you
                        mvn clean install
                '''
           }



           
           post {
               failure {
                        slackSend(
                            channel: '#all-manga2you',
                            message: " unit test FAILED for ${env.JOB_NAME} #${env.BUILD_NUMBER}"
                        )
                }
           }
        }
        

        stage('OCA Scan') {
            steps {
                        sh '''
                            cd backend_manga2you
                            trivy fs --severity HIGH,CRITICAL --format json --exit-code 1 .
                        '''
            }
            post {
                failure {
                        slackSend(
                            channel: '#all-manga2you',
                            message: "❌ Trivy scan FAILED for ${env.JOB_NAME} #${env.BUILD_NUMBER}"
                        )
                }
            }
        }
        
     
     stage("SAST Scans") {
         steps {
                    sh '''
                     cd backend_manga2you
                     snyk auth ${SNYK_TOKEN}
                     snyk code test --severity-threshold=high
                    '''
}

post {
    failure {
        slackSend(
        channel: '#all-manga2you',
        message: "SAST Scans Failed for ${env.JOB_NAME} ${env.BUILD_NUMBER}"
    )
}
}
}
     
     
     
        stage('Building The Image'){
            steps {
                        // Build the image
                        sh '''
                        cd backend_manga2you
                        docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} .
                        '''
            }
        }
        
        
        stage('Pushing To Docker Hub'){
            steps {
                        // push image to docker hub
                        sh '''
                        echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin
                        
                        docker tag ${IMAGE_NAME}:${BUILD_NUMBER} ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${BUILD_NUMBER}
                        docker push ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${BUILD_NUMBER}
                        '''
            }
        }
        
        
        
        stage('Deploy to Server'){
            steps {
                        // push image to docker hub
                        sh '''
                        git clone https://github.com/saberBenhamda0/monolithic-devops-project.git
                        cd monolithic-devops-project/infrastructure/base
                        
                        # Configure Git locally
                        git config --global user.email "saberbenhamda0@gmail.com"
                        git config --global user.name "136007584"
                        git config --global url.https://"${GITHUB_TOKEN}"@github.com/.insteadOf https://github.com/
                        
                        sed -i "s|image: .*|image: saberbenhamda0/backend_manga2you:${BUILD_NUMBER}|" deployment.yaml
                        git commit -am "Update backend image to ${BUILD_NUMBER}"
                        git push -u origin main
                        '''
            }
        }
    
        
        
    }
    
    post {
        success {
            slackSend(
                channel: '#all-manga2you',
                message: "pipeline success FAILED for ${env.JOB_NAME} #${env.BUILD_NUMBER}"
            )
        }
        failure {
            slackSend(
                channel: '#all-manga2you',
                message: " pipeline failed for ${env.JOB_NAME} #${env.BUILD_NUMBER}"
            )
}
    }
}