apiVersion: v1
kind: ConfigMap
metadata:
  name: production-datasource
  labels:
    grafana_datasource: "1"
data:
  production-datasource.yaml: |
    apiVersion: 1

    datasources:
      - name: PrometheusfromconfigMap
        type: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus:9090
        isDefault: true
        editable: false