apiVersion: v1
kind: ConfigMap
metadata:
  name: production-datasource
  labels:
    grafana_datasource: "1"
data:
  production-datasource.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus:9090
        isDefault: false
        version: 1
        editable: false
        jsonData:
          {}
      - name: Prometheus2
        type: prometheus
        uid: prometheus2
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus:9090
        isDefault: false
        version: 1
        editable: false
        jsonData:
          {}