pipeline {
    agent { label 'gitops-agent' }

    stages {
        stage('Checkout') {
            steps {
                sh 'git clone https://github.com/saberBenhamda0/monolithic-devops-project'
            }
        }
        
        /*   
        // validate the yaml syntax
        stage('YAML Lint') {
            steps {
                sh 'yamllint monolithic-devops-project/infrastructure/overlays/prod/'
            }
        }
        */
        
        /*
        //Schema Validation against Kubernetes API
        stage('Schema Validation') {
            steps {
                sh 'kubeconform -strict monolithic-devops-project/infrastructure/overlays/prod/'
            }
        }
        */
        
        /*
        // validating kustomize 
        stage('Kustomize Dry-run') {
            steps {
                sh 'kustomize build monolithic-devops-project/infrastructure/overlays/prod/'
            }
        }*/

/*
        // leaked secret detecion in both code in commit history
        stage('Secret Detection') {
            steps {
                sh 'gitleaks detect --source ./monolithic-devops-project/ --verbose'
            }
        }
*/
/*
        stage('Security Scan') {
            steps {
                // It's a tool made specifically for Kubernetes manifests.
                // It checks your YAML files for security and best practice issues like
                sh 'kube-linter lint ./monolithic-devops-project/infrastructure/'
                
                // the below is for terraform
                //sh 'checkov -d ./manifests/'
            }
        }
*/
    }
    post {
        failure {
            echo 'Pipeline failed! Fix the errors before merging.'
        }
        success {
            echo 'All checks passed! Ready to merge.'
        }
    }
}
