pipeline {
    agent { label 'gitops-agent' }

    stages {
        stage('Checkout') {
            steps {
                sh 'git clone https://github.com/saberBenhamda0/monolithic-devops-project'
            }
        }

        stage('PR Checks') {
            when {
                allOf {
                    changeRequest()
                    changeRequest target: 'main'
                }
            }
            stages {
                
                // validate the yaml syntax
                stage('YAML Lint') {
                    steps {
                        sh 'yamllint monolithic-devops-project/infrastructure/overlays/prod/'
                    }
                }

                // Schema Validation against Kubernetes API
                stage('Schema Validation') {
                    steps {
                        sh 'kubeconform -strict monolithic-devops-project/infrastructure/overlays/prod/'
                    }
                }

                // validating kustomize
                stage('Kustomize Dry-run') {
                    steps {
                        sh 'kustomize build monolithic-devops-project/infrastructure/overlays/prod/'
                    }
                }

                // leaked secret detection in both code and commit history
                stage('Secret Detection') {
                    steps {
                        sh 'gitleaks detect --source ./monolithic-devops-project/ --verbose'
                    }
                }

                stage('Security Scan') {
                    steps {
                        // checks Kubernetes manifests for security and best practice issues
                        sh 'kube-linter lint ./monolithic-devops-project/infrastructure/'
                        
                        // uncomment below for terraform
                        // sh 'checkov -d ./manifests/'
                    }
                }
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed! Fix the errors before merging.'
        }
        success {
            echo 'All checks passed! Ready to merge.'
        }
    }
}