apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- hpa.yaml
- rbac/backend/sa.yaml
- rbac/backend/role.yaml
- rbac/backend/role-biding.yaml
configMapGenerator:
- envs:
  - config.properties
  name: base-backend-manga2you-env-variables
labels:
- includeSelectors: true
  pairs:
    app: backend-manga2you
