server:
  dev:
    enabled: true

  extraSecretEnvironmentVars:
    - envName: AWS_ACCESS_KEY_ID
      secretName: vault-init-creds
      secretKey: AWS_ACCESS_KEY_ID
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: vault-init-creds
      secretKey: AWS_SECRET_ACCESS_KEY
    - envName: AWS_DEFAULT_REGION
      secretName: vault-init-creds
      secretKey: AWS_DEFAULT_REGION

  volumes:
    - name: init-script
      configMap:
        name: vault-init-script
        defaultMode: 0755
  volumeMounts:
    - name: init-script
      mountPath: /scripts
  postStart:
    - /bin/sh
    - -c
    - /scripts/init.sh