apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-backend-manga2you
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saberBenhamda0/monolithic-devops-project.git
    targetRevision: HEAD
    path: backend/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  
